// css_chirp_rom.v - CSK generator lookup table
//
// Holds the quantized chirp sequences for all four chirp indices (m = 1..4).
// Each bank stores 4 subchirps x TSUB(38) complex samples, 6-bit signed I/Q.
// Word format: {re[5:0], im[5:0]}, generated by scripts/gen_golden_vectors.py
// and matching matlab chirpSequenceReal_tofile.txt / ...Imag_tofile.txt.
module css_chirp_rom (
    input  wire       clk,
    input  wire [1:0] bank,      // chirp index m-1
    input  wire [1:0] sub,       // subchirp k = QPSK symbol position in group
    input  wire [5:0] n,         // sample index within subchirp
    output wire [15:0] q         // {re[7:0], im[7:0]} sign-extended 6-bit fields
);
    reg [15:0] mem [0:607];      // 4 banks x 152 words
    reg [15:0] q_r;
    wire [9:0] addr = bank * 10'd152 + sub * 10'd38 + {4'b0, n};

    initial begin
        $readmemh("chirp_rom.hex", mem);
    end

    always @(posedge clk) begin
        q_r <= mem[addr];
    end

    assign q = q_r;
endmodule
